### ISSUE TITLE
Issues with Plain Text Output Format

### ISSUE THREAD

**Issue by ripkim** [dejbug/ff-tab-lister#2]
Hi,
Thanks for making Tab Lister!

I'm having problems using your extension when using a custom plain text output format and then pasting from the clipboard into a Gmail compose window.

My custom output format is as follows:

<pre><code>{TITLE}\n{URL}\n
</code></pre>

Ideally, Tab Lister would provide me with the tab title on one line, and then on a new line directly below, I would like to see the URL.

For instance:

<pre><code>Google
https://www.google.com/
</code></pre>

Instead, I get the following (assume a browser window with two tabs open to Google's homepage):

<pre><code>Google
https://www.google.com/\nGoogle
https://www.google.com/\n
</code></pre>

I've tried variations using other special escapes, but end up with similar results.

Please let me know if you have any advice, thanks!

**Comment by dejbug** [comment]
hi there! thank you for your detailed feedback! this one is a major catch! :+1:

the way you thought it would work is exactly the way it should have worked. i'm very sorry it didn't!

i've uploaded a new version which should fix your issue. sorry for the trouble! and thanks again for catching this! don't hesitate to open new issues as they arise!

just amazing how many bugs i could work into so little code! :smile: my apologies. JavaScript is far from being my primary language, so i'm still missing little subtleties....
