### ISSUE TITLE
Is it possible to provide text/html code to go before and after the entire list?

### ISSUE THREAD

**Issue by etech0** [dejbug/ff-tab-lister#3]
This looks like it might be just what I"m using for. 

Is it possible to provide html code to go before and after the entire list (as opposed to going before and after each item?)

Thanks!

**Comment by dejbug** [comment]
hi! thank you for asking! could you try inserting an CRLF sequence i.e. '/r/n'? it should be properly handled by the script. cheers!

**Comment by dejbug** [comment]
oh, sorry! I just got around reading the new issue. this would be new but it's easy enough to add. I'll do it first thing tomorrow just for you :)

**Comment by etech0** [comment]
Awesome, thanks so much! Looking forward...

**Comment by dejbug** [comment]
ok. sorries for the delay. mozilla switched to a new tool while I wasn't looking so I had to fiddle with that first.

the new version is uploaded and is currently **pending review**. it should be available soon.

_as for the previous "shift-enter" issue. I realized too late that you must have meant "soft breaks" or non-breaking spaces, in which case just insert an "&nbsp;" html entity. no need for escapes. but you've figured that one out yourself already._

hope this works! cheers!

**Comment by etech0** [comment]
Thanks for taking care of that! I can't wait for the new feature...

Meanwhile, regarding the shift-enter, what I'm actually looking for is not
a non-breaking space, but rather, a non-breaking line break (if that's what
you call it). You can get that in MS Word by pressing shift-enter. " "
doesn't do this. Any ideas how to do it?

Thanks!

**Comment by dejbug** [comment]
oh! well now I'm feeling really slow! :) but hmm. if I got you right this time--and I'm increasingly more sorry, really, every time I don't!--then you should either remove all `<br>` (or `<br />`) tags and leave only the `\r\n`, or do this the other way around. you could also try, in the former case, to change every `\r\n` to either just an `\n` or even just an `\r`

 if that didn't do it, then I would finally have to quit supposing and start asking you real questions! :smile: 

I saw that my firefox had silently updated the addon. please don't hesitate to tell me if something went wrong on your side. thank you!

**Comment by dejbug** [comment]
sorry again. in my previous post I was too quick & careless with the github editor, and didn't escape the BR tag (with either a backslash or with backquotes). now the post should make some sense.

**Comment by dejbug** [comment]
seems to be ok then :smile:
