### ISSUE TITLE
Enable addon in private browsing

### ISSUE THREAD

**Issue by AndreWaehlisch** [dejbug/ff-tab-lister#4]
The addon is disabled in private browsing (the icon won't even show up). [This stackoverflow post](http://stackoverflow.com/questions/28104763/how-to-allow-addons-on-firefox-private-browsing) claims you need to add the following line to the _package.json_: `"permissions": {"private-browsing": true},`

ps.: Thanks for this addon!

**Comment by dejbug** [comment]
Thank you!! I'm so sorry for the delay. I'm going to do it rightaway.
