### ISSUE TITLE
replace double-quotes in title with &quot;

### ISSUE THREAD

**Issue by rubaboo** [dejbug/ff-tab-lister#5]
I have defined the tab format as follows, but it breaks if there is a double-quote in the title.

    <opml version="2.0"><body><outline text="[link: {TITLE}|{URL}]"></outline></body></opml>\r\n

**Comment by dejbug** [comment]
Thank you! Good catch! Sorry for the delay.
I'm thinking we should add a title-preprocessing step to the options dialog.
